In [18]:
import sys
print(sys.executable)
!{sys.executable} -m pip install scikit-learn

c:\Users\MuhammadAbdullah\AppData\Local\Python\pythoncore-3.11-64\python.exe
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\muhammadabdullah\appdata\local\python\pythoncore-3.11-64\lib\site-packages (from scikit-learn) (2.4.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 3.4 MB/s eta 0:00:00
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB 3.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.4/8.1 MB 2.5 MB/s eta 0:00:04
   -- ------------------------------------- 0.6/8.1 MB 2.3 MB/s eta 0:00:04
   ---- ----------------------------------- 0.8/8.1 MB 2.1 MB/s eta 0:00:04
   ----- ---------------------------------- 1.0/8.1 MB 2.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.2/8.1 MB 2.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.4/8.1 MB 2.0 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/8.1 MB 1.9 MB/s eta 0:00:04
   --------- ------------------------------ 1.9/8.1 MB 1.9 MB/s eta 0:00:04
   --------- ------------------------------ 1.9/8.1 MB 1.9 MB/s eta 0:00:04
   ---------- ----------------------------- 2.0/8.1 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.2/8.1 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 2.5/8.1 MB 1.9 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.1 MB 1.9 MB/s eta 0:00:03
   ------------- -------------------------- 2.7/8.1 MB 1.9 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.1 MB 1.9 MB/s eta 0:00:03
   -------------- ------------------------- 3.0/8.1 MB 1.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.2/8.1 MB 1.9 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.1 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 3.5/8.1 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 3.6/8.1 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.0/8.1 MB 1.9 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.1 MB 1.8 MB/s eta 0:00:02
   ------------------------ --------------- 4.9/8.1 MB 1.8 MB/s eta 0:00:02
   -------------------------- ------------- 5.3/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.1 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 5.6/8.1 MB 1.8 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 6.5/8.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------- ----- 6.9/8.1 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.1 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.1 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 7.5/8.1 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 7.8/8.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 1.8 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB 8.6 MB/s eta 0:00:05
   ---------------------------------------- 0.4/36.6 MB 4.0 MB/s eta 0:00:09
    --------------------------------------- 0.5/36.6 MB 3.0 MB/s eta 0:00:12
    --------------------------------------- 0.6/36.6 MB 2.7 MB/s eta 0:00:14
    --------------------------------------- 0.6/36.6 MB 2.7 MB/s eta 0:00:14
   - -------------------------------------- 1.0/36.6 MB 2.3 MB/s eta 0:00:16
   - -------------------------------------- 1.1/36.6 MB 2.2 MB/s eta 0:00:17
   - -------------------------------------- 1.2/36.6 MB 2.2 MB/s eta 0:00:17
   - -------------------------------------- 1.4/36.6 MB 2.1 MB/s eta 0:00:17
   - -------------------------------------- 1.6/36.6 MB 2.1 MB/s eta 0:00:17
   - -------------------------------------- 1.8/36.6 MB 2.0 MB/s eta 0:00:18
   -- ------------------------------------- 1.9/36.6 MB 2.0 MB/s eta 0:00:17
   -- ------------------------------------- 2.1/36.6 MB 2.0 MB/s eta 0:00:18
   -- ------------------------------------- 2.3/36.6 MB 2.0 MB/s eta 0:00:18
   -- ------------------------------------- 2.4/36.6 MB 2.0 MB/s eta 0:00:18
   -- ------------------------------------- 2.5/36.6 MB 2.0 MB/s eta 0:00:18
   -- ------------------------------------- 2.6/36.6 MB 2.0 MB/s eta 0:00:18
   --- ------------------------------------ 2.8/36.6 MB 1.9 MB/s eta 0:00:18
   --- ------------------------------------ 3.1/36.6 MB 1.9 MB/s eta 0:00:18
   --- ------------------------------------ 3.4/36.6 MB 1.9 MB/s eta 0:00:18
   --- ------------------------------------ 3.6/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 3.7/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 3.8/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 3.9/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.0/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.1/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.2/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.3/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.4/36.6 MB 1.9 MB/s eta 0:00:18
   ---- ----------------------------------- 4.5/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 4.7/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 4.8/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 5.0/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 5.2/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 5.3/36.6 MB 1.9 MB/s eta 0:00:17
   ----- ---------------------------------- 5.4/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 5.5/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 5.6/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 5.7/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 5.9/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.0/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.2/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.3/36.6 MB 1.9 MB/s eta 0:00:17
   ------ --------------------------------- 6.4/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.5/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.6/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.7/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.8/36.6 MB 1.9 MB/s eta 0:00:17
   ------- -------------------------------- 6.9/36.6 MB 1.9 MB/s eta 0:00:16
   ------- -------------------------------- 7.1/36.6 MB 1.9 MB/s eta 0:00:16
   ------- -------------------------------- 7.2/36.6 MB 1.9 MB/s eta 0:00:16
   ------- -------------------------------- 7.3/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 7.4/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 7.6/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 7.6/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 7.7/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 7.9/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 8.0/36.6 MB 1.9 MB/s eta 0:00:16
   -------- ------------------------------- 8.2/36.6 MB 1.9 MB/s eta 0:00:16
   --------- ------------------------------ 8.3/36.6 MB 1.9 MB/s eta 0:00:16
   --------- ------------------------------ 8.3/36.6 MB 1.9 MB/s eta 0:00:16
   --------- ------------------------------ 8.4/36.6 MB 1.9 MB/s eta 0:00:16
   --------- ------------------------------ 8.5/36.6 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.6/36.6 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.7/36.6 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.8/36.6 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 8.9/36.6 MB 1.8 MB/s eta 0:00:16
   --------- ------------------------------ 9.0/36.6 MB 1.8 MB/s eta 0:00:15
   --------- ------------------------------ 9.1/36.6 MB 1.8 MB/s eta 0:00:15
   --------- ------------------------------ 9.1/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.2/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.3/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.4/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.5/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.5/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.7/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.7/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.8/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 9.9/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 10.0/36.6 MB 1.8 MB/s eta 0:00:15
   ---------- ----------------------------- 10.1/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.2/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.3/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.4/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.4/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.5/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.6/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.7/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.8/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 10.9/36.6 MB 1.8 MB/s eta 0:00:15
   ----------- ---------------------------- 11.0/36.6 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.0/36.6 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.2/36.6 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.2/36.6 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.3/36.6 MB 1.8 MB/s eta 0:00:15
   ------------ --------------------------- 11.4/36.6 MB 1.8 MB/s eta 0:00:14
   ------------ --------------------------- 11.5/36.6 MB 1.8 MB/s eta 0:00:14
   ------------ --------------------------- 11.6/36.6 MB 1.8 MB/s eta 0:00:14
   ------------ --------------------------- 11.7/36.6 MB 1.8 MB/s eta 0:00:14
   ------------ --------------------------- 11.8/36.6 MB 1.8 MB/s eta 0:00:14
   ------------ --------------------------- 11.9/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.0/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.1/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.1/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.4/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.5/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.5/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.6/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.7/36.6 MB 1.8 MB/s eta 0:00:14
   ------------- -------------------------- 12.8/36.6 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 12.9/36.6 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.0/36.6 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.1/36.6 MB 1.8 MB/s eta 0:00:14
   -------------- ------------------------- 13.2/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.3/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.4/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.4/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.5/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.6/36.6 MB 1.8 MB/s eta 0:00:13
   -------------- ------------------------- 13.7/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 13.8/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 13.9/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.0/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.0/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.1/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.2/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.3/36.6 MB 1.8 MB/s eta 0:00:13
   --------------- ------------------------ 14.5/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.7/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 14.9/36.6 MB 1.8 MB/s eta 0:00:13
   ---------------- ----------------------- 15.1/36.6 MB 1.8 MB/s eta 0:00:13
   ----------------- ---------------------- 15.6/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 15.8/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 15.9/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 15.9/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.0/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.1/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.2/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.3/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.4/36.6 MB 1.8 MB/s eta 0:00:12
   ----------------- ---------------------- 16.4/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 16.5/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 16.6/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 16.7/36.6 MB 1.8 MB/s eta 0:00:12
   ------------------ --------------------- 16.8/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 16.9/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.0/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.0/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.2/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.2/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.3/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------ --------------------- 17.4/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.5/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.6/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.7/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.8/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.8/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 17.9/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.0/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.1/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.2/36.6 MB 1.8 MB/s eta 0:00:11
   ------------------- -------------------- 18.3/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.4/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.4/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.4/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.4/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.6/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.6/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.6/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.8/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 18.8/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 19.0/36.6 MB 1.8 MB/s eta 0:00:11
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   -------------------- ------------------- 19.2/36.6 MB 1.7 MB/s eta 0:00:10
   --------------------- ------------------ 19.4/36.6 MB 1.7 MB/s eta 0:00:11
   --------------------- ------------------ 19.4/36.6 MB 1.7 MB/s eta 0:00:11
   --------------------- ------------------ 19.7/36.6 MB 1.7 MB/s eta 0:00:11
   --------------------- ------------------ 19.8/36.6 MB 1.7 MB/s eta 0:00:11
   --------------------- ------------------ 19.9/36.6 MB 1.7 MB/s eta 0:00:10
   --------------------- ------------------ 20.0/36.6 MB 1.7 MB/s eta 0:00:10
   --------------------- ------------------ 20.1/36.6 MB 1.7 MB/s eta 0:00:10
   --------------------- ------------------ 20.1/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.2/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.2/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.2/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.2/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.3/36.6 MB 1.6 MB/s eta 0:00:11
   ---------------------- ----------------- 20.4/36.6 MB 1.6 MB/s eta 0:00:11
   ---------------------- ----------------- 20.8/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 20.8/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 21.0/36.6 MB 1.7 MB/s eta 0:00:10
   ---------------------- ----------------- 21.0/36.6 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.1/36.6 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.2/36.6 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.3/36.6 MB 1.7 MB/s eta 0:00:10
   ----------------------- ---------------- 21.4/36.6 MB 1.7 MB/s eta 0:00:10

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("./src/cars.csv")
df.sample(10)

          brand  km_driven    fuel         owner  selling_price
351     Renault      84722  Petrol  Second Owner         488687
329      Maruti      94829  Petrol   First Owner         271232
344  Land Rover      31170  Petrol  Second Owner        1843191
930        Tata     219480  Petrol   Third Owner         334304
575      Toyota     134147  Diesel   First Owner         786155
950       Honda     204452  Petrol   First Owner         638298
341    Mahindra     168531  Diesel   First Owner         445497
675        Audi     112336  Diesel   First Owner        1898857
944       Honda     150307  Diesel   Third Owner         645044
494     Hyundai     124488  Petrol   First Owner         215574

In [8]:
df['brand'].value_counts()

brand
Maruti           187
Hyundai          136
Honda            119
Toyota           101
Tata              97
Mahindra          80
Ford              60
Renault           49
Nissan            19
Skoda             17
MG                15
Mercedes-Benz     13
Chevrolet         12
Volkswagen        11
Jeep              10
Datsun            10
Fiat               9
Mitsubishi         8
BMW                7
Kia                6
Isuzu              6
Audi               6
Land Rover         6
Lexus              5
Jaguar             5
Porsche            4
Volvo              2
Name: count, dtype: int64

In [9]:
df['brand'].nunique()

27

In [10]:
df['fuel'].value_counts()

fuel
Petrol    553
Diesel    335
CNG        76
LPG        36
Name: count, dtype: int64

In [11]:
df['owner'].value_counts()

owner
First Owner             520
Second Owner            280
Third Owner             120
Fourth & Above Owner     70
Test Drive Car           10
Name: count, dtype: int64

# OHE Using Pandas

In [13]:
pd.get_dummies(df, columns=['fuel', 'owner'], dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Honda,55707,194985,0,0,0,1,0,0,1,0,0
1,Tata,121727,261339,0,1,0,0,1,0,0,0,0
2,Toyota,221524,714366,0,1,0,0,0,0,0,0,1
3,Maruti,144531,441755,0,0,0,1,0,1,0,0,0
4,Hyundai,53482,292707,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Honda,88577,593520,0,0,0,1,1,0,0,0,0
996,Toyota,142803,681777,0,1,0,0,0,0,1,0,0
997,Mahindra,119270,318502,0,0,0,1,1,0,0,0,0
998,Skoda,151962,615700,0,0,0,1,1,0,0,0,0
999,Tata,171159,514713,0,0,0,1,0,0,1,0,0

In [14]:
pd.get_dummies(df, columns=['fuel', 'owner'], dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Honda,55707,194985,0,0,1,0,1,0,0
1,Tata,121727,261339,1,0,0,0,0,0,0
2,Toyota,221524,714366,1,0,0,0,0,0,1
3,Maruti,144531,441755,0,0,1,1,0,0,0
4,Hyundai,53482,292707,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
995,Honda,88577,593520,0,0,1,0,0,0,0
996,Toyota,142803,681777,1,0,0,0,1,0,0
997,Mahindra,119270,318502,0,0,1,0,0,0,0
998,Skoda,151962,615700,0,0,1,0,0,0,0
999,Tata,171159,514713,0,0,1,0,1,0,0

- pandas doesn't remember the position of the columns that's why we can not use it for ML we will use scikit learn

# OHE Using Scikit Learn

In [15]:
df.head()

     brand  km_driven    fuel                 owner  selling_price
0    Honda      55707  Petrol          Second Owner         194985
1     Tata     121727  Diesel           First Owner         261339
2   Toyota     221524  Diesel           Third Owner         714366
3   Maruti     144531  Petrol  Fourth & Above Owner         441755
4  Hyundai      53482     LPG           First Owner         292707

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size=0.2, random_state=42)

In [21]:
X_train.head()

        brand  km_driven    fuel         owner
29   Mahindra      93947  Diesel  Second Owner
535    Maruti     220259  Petrol   Third Owner
695   Hyundai     120596  Diesel  Second Owner
557    Maruti     129396  Diesel   Third Owner
836    Datsun     159339  Petrol   First Owner

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
ohe = OneHotEncoder(drop='first')

In [44]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel', 'owner']]).toarray()

In [45]:
X_train_new.shape

(800, 7)

In [46]:
X_train[['brand','km_driven']].values

array([['Mahindra', 93947],
       ['Maruti', 220259],
       ['Hyundai', 120596],
       ...,
       ['Hyundai', 38565],
       ['Toyota', 79411],
       ['Toyota', 63138]], shape=(800, 2), dtype=object)

In [47]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(800, 9)

In [49]:
counts_brand = df["brand"].value_counts()
threshold = 49
replace = counts_brand[counts_brand <= threshold].index 
pd.get_dummies(df['brand'].replace(replace, 'other'), dtype=int, drop_first=True)

     Honda  Hyundai  Mahindra  Maruti  Tata  Toyota  other
0        1        0         0       0     0       0      0
1        0        0         0       0     1       0      0
2        0        0         0       0     0       1      0
3        0        0         0       1     0       0      0
4        0        1         0       0     0       0      0
..     ...      ...       ...     ...   ...     ...    ...
995      1        0         0       0     0       0      0
996      0        0         0       0     0       1      0
997      0        0         1       0     0       0      0
998      0        0         0       0     0       0      1
999      0        0         0       0     1       0      0

[1000 rows x 7 columns]